### ISSUE TITLE
Installation help?

### ISSUE THREAD

**Issue by Silent-Hunter** [GyozaGuy/Skype-Electron#4]
The readme doesn't explain how to install it, running build.sh gives me this:

silent@TERMINAL-BMRF-9 ~/Skype-Electron $ sh build.sh
build.sh: line 4: electron-packager: command not found

**Comment by GyozaGuy** [comment]
Hello! I guess I should add that in the readme shouldn't I?

The build script simply calls electron-packager, so it needs to be installed first.  Install electron-packager like so:
`npm install -g electron-packager`

**Comment by GyozaGuy** [comment]
Fixed with commit 44ad808.
